### ISSUE TITLE
Please advise how you use Grid fieldtype on frontend Workshop form.

### ISSUE THREAD

**Issue by bgarrant** [statamic/workshop#16]
**Is your feature request related to a problem? Please describe.**
I have a site that we need to allow a client to add data to a grid from a frontend Workshop form. Looks like people have been able to do this before https://statamic.com/forum/1850-grid-data-not-saving-from-front-end-prof, https://statamic.com/forum/1357-edit-grid-fields-or-table-field-on-the-f. 

**Describe the solution you'd like**
We need to know how to add a grid fieldtype to a Workshop frontend form.  There must be a way this can be done already.  Something like you see in the backend where you can just add rows.

https://cl.ly/320t0L3h0U0Z

**Describe alternatives you've considered**
I am not great at JS but I am sure there must be a way to do this.

**Additional context**

**Comment by danielfowler** [comment]
@bgarrant You can use nested array inputs to save data in the same format as what your grid fieldtype will allow.

[Here's a CodePen that shows how I recreated one of my grid fieldsets using Workshop](https://codepen.io/danielfowler/pen/YjExWY). The resultant YAML looks like this:

```YAML
crew:
  1:
    name: John Doe
    role: Director
    responsibilities: Make the show awesome.
  2:
    name: Jane Crow
    role: Choreographer
    responsibilities: Teach people to dance.
```
